### ISSUE TITLE
Tests failed with latest jedi 

### ISSUE THREAD

**Issue by ghost** [vheon/JediHTTP#54]
Hi,

JediHTTP self tests generate the following error message with the latest jedi (0.12.0):
```
FAIL: jedihttp.tests.handlers_test.test_completion_socket_module

Expected: (a sequence containing a dictionary containing ['name': 'connect'] and a sequence containing a dictionary containing ['name': 'connect_ex'])
    but: a sequence containing a dictionary containing ['name': 'connect'] was <[]>
```

**Comment by vheon** [comment]
Hi, sorry for the late response. That is exactly why we fix the version of jedi in this project and don't advertise to be an http wrapper around whichever version of Jedi 😅.

Anyway, are you using JediHTTP outside of YouCompleteMe? Because the plan (if not already done, my time in OSS is very limited lately) is to drop JediHTTP in YouCompleteMe since the driving reasons for JediHTTP were limitations that we had to overcome in YouCompleteMe but since the latest version of Jedi do those on its own we don't have any compelling reason to invest time in this. If instead you use JediHTTP outside of YouCompleteMe and this blocks you somehow PR are always welcome.

**Comment by ghost** [comment]
No I am using JediHTTP with YCM. I guess after updating the system (jedi included), I was unable to build this package. 

If, as you said, the latest version of jedi can do things on its own, then I agree that there's little point to invest time on this.
