### ISSUE TITLE
Can't find jedihttp in the project

### ISSUE THREAD

**Issue by RobertK83** [vheon/JediHTTP#55]
I want to start jedi but no such file...
python /path/to/JediHTTP/jedihttp.py

Maybe I'm blind :/

**Comment by micbou** [comment]
You are supposed to start JediHTTP like this (the last `/` can be omitted):
```sh
python /path/to/JediHTTP/jedihttp/
```
Note that JediHTTP is probably not going to be maintained anymore as YCM dropped its use in PR https://github.com/Valloric/ycmd/pull/1028 (I am saying probably because @vheon is the project's author and that's up to him to decide if he still want to maintain it or not).
